### ISSUE TITLE
Sometimes Pod Failure

### ISSUE THREAD

**Issue by Y0ngg4n** [kubernetes-sigs/descheduler#743]
**What version of descheduler are you using?**

descheduler version: v0.23.0

**Does this issue reproduce with the latest release?**
Yes

**Which descheduler CLI options are you using?**

**Please provide a copy of your descheduler policy config file**
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: default
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: descheduler
      version: "0.23.1"
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
      interval: 1m
  values:
    schedule: "*/10 * * * *"
    image:
      repository: k8s.gcr.io/descheduler/descheduler
      tag: "v0.23.0"
    backoffLimit: 2
    successfulJobsHistoryLimit: 2
    failedJobsHistoryLimit: 2
    deschedulerPolicy:
      strategies:
        RemoveDuplicates:
          enabled: true
        RemovePodsViolatingNodeTaints:
          enabled: true
        RemovePodsViolatingNodeAffinity:
          enabled: true
          params:
            nodeAffinityType:
              - requiredDuringSchedulingIgnoredDuringExecution
        RemovePodsViolatingInterPodAntiAffinity:
          enabled: true
        LowNodeUtilization:
          enabled: true
          params:
            nodeResourceUtilizationThresholds:
              thresholds:
                cpu: 40
                memory: 40
                pods: 40
              targetThresholds:
                cpu: 60
                memory: 60
                pods: 60
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"archive", BuildDate:"2022-01-27T18:26:18Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

</pre></details>

**What did you do?**
Just installed it

**What did you expect to see?**
Every pod successfully terminating

**What did you see instead?**
```
I0225 15:20:16.597946 1 node.go:169] "Pod fits on node" pod="kubegres-system/kubegres-controller-manager-75db85776-2xrxn" node="kubernetes-worker-02"
I0225 15:20:16.597968 1 node.go:169] "Pod fits on node" pod="monitoring/prometheus-operator-68467b5c68-g2wqf" node="kubernetes-worker-02"
I0225 15:20:16.597998 1 node.go:169] "Pod fits on node" pod="websites/nginx-static-55d776d678-qj28m" node="kubernetes-worker-02"
I0225 15:20:16.598020 1 node.go:169] "Pod fits on node" pod="volt/volt-rest-api-599949d777-lgr6t" node="kubernetes-worker-02"
I0225 15:20:16.598036 1 node.go:169] "Pod fits on node" pod="volt/volt-web-86bd775575-d28kn" node="kubernetes-worker-02"
I0225 15:20:16.598048 1 node.go:169] "Pod fits on node" pod="media/jellyfin-f5d858979-jdb5b" node="kubernetes-worker-02"
I0225 15:20:16.598061 1 node.go:169] "Pod fits on node" pod="media/prowlarr-bdf9bbf9b-lbkpr" node="kubernetes-worker-02"
I0225 15:20:16.598071 1 node.go:169] "Pod fits on node" pod="kubegres-system/kubegres-1-0" node="kubernetes-worker-02"
I0225 15:20:16.598097 1 node.go:169] "Pod fits on node" pod="media/radarr-d74b455bc-6xb92" node="kubernetes-worker-02"
I0225 15:20:16.598123 1 node.go:169] "Pod fits on node" pod="jitsi/jitsi-jitsi-meet-jvb-787cd69665-pkzxz" node="kubernetes-worker-02"
I0225 15:20:16.598149 1 node.go:169] "Pod fits on node" pod="monitoring/blackbox-exporter-7d89b9b799-cbxnt" node="kubernetes-worker-02"
I0225 15:20:16.598163 1 node.go:169] "Pod fits on node" pod="websites/ghost-58ff994-zms9d" node="kubernetes-worker-02"
I0225 15:20:16.598188 1 node.go:169] "Pod fits on node" pod="websites/oblivioncoding-website-ffd849bb-x5gt2" node="kubernetes-worker-02"
I0225 15:20:16.598203 1 node.go:169] "Pod fits on node" pod="websites/fickipedia-mediawiki-64655f6955-zmp67" node="kubernetes-worker-02"
I0225 15:20:16.598224 1 node.go:169] "Pod fits on node" pod="jitsi/jitsi-jitsi-meet-jicofo-57c86f4886-gndjj" node="kubernetes-worker-02"
I0225 15:20:16.598238 1 node.go:169] "Pod fits on node" pod="media/ombi-76567f9b7f-dfmqh" node="kubernetes-worker-02"
I0225 15:20:16.598262 1 node.go:169] "Pod fits on node" pod="jitsi/jitsi-prosody-0" node="kubernetes-worker-02"
I0225 15:20:16.598279 1 node.go:169] "Pod fits on node" pod="kubegres-system/kubegres-24-0" node="kubernetes-worker-02"
I0225 15:20:16.598302 1 node.go:169] "Pod fits on node" pod="default/metallb-controller-c55c89d-r5m8v" node="kubernetes-worker-02"
I0225 15:20:16.598317 1 node.go:169] "Pod fits on node" pod="cockroach-operator-system/cockroach-operator-manager-77f4957cdf-nqz7x" node="kubernetes-worker-02"
I0225 15:20:16.598337 1 node.go:169] "Pod fits on node" pod="jitsi/jitsi-jitsi-meet-web-5f55f4868b-frzbb" node="kubernetes-worker-02"
I0225 15:20:16.598359 1 node.go:169] "Pod fits on node" pod="cert-manager/cert-manager-cainjector-747cfdfd87-d6h9z" node="kubernetes-worker-02"
I0225 15:20:16.598376 1 node.go:169] "Pod fits on node" pod="matrix/element-5c54494cd-bfdwz" node="kubernetes-worker-02"
I0225 15:20:16.598392 1 node.go:169] "Pod fits on node" pod="cert-manager/cert-manager-webhook-67cb765ff6-f9p62" node="kubernetes-worker-02"
I0225 15:20:16.598408 1 node.go:169] "Pod fits on node" pod="cert-manager/cert-manager-5b6d4f8d44-9v9dn" node="kubernetes-worker-02"
I0225 15:20:16.598429 1 node.go:169] "Pod fits on node" pod="vaultwarden/vaultwarden-7b7ccd55d7-fdv8b" node="kubernetes-worker-02"
I0225 15:20:16.598442 1 node.go:169] "Pod fits on node" pod="matrix/synapse-688c9c4fdb-9sfgp" node="kubernetes-worker-02"
I0225 15:20:16.598455 1 node.go:169] "Pod fits on node" pod="default/nfs-subdir-external-provisioner-84c486db85-sdmf2" node="kubernetes-worker-02"
I0225 15:20:16.598472 1 node.go:169] "Pod fits on node" pod="monitoring/kube-state-metrics-86b69f4775-2xn7b" node="kubernetes-worker-02"
I0225 15:20:16.598489 1 node_taint.go:93] "Processing node" node="kubernetes-cp-01"
I0225 15:20:16.598570 1 node_taint.go:93] "Processing node" node="kubernetes-worker-01"
I0225 15:20:16.598683 1 node_taint.go:93] "Processing node" node="kubernetes-worker-02"
I0225 15:20:16.599057 1 nodeutilization.go:164] "Node is underutilized" node="kubernetes-cp-01" usage=map[cpu:572m memory:1172Mi pods:11] usagePercentage=map[cpu:29.333333333333332 memory:32.24167501278783 pods:10]
I0225 15:20:16.599094 1 nodeutilization.go:167] "Node is overutilized" node="kubernetes-worker-01" usage=map[cpu:2112m memory:2719Mi pods:22] usagePercentage=map[cpu:71.59322033898304 memory:17.604589721787065 pods:20]
I0225 15:20:16.599113 1 nodeutilization.go:167] "Node is overutilized" node="kubernetes-worker-02" usage=map[cpu:2818m memory:4648Mi pods:54] usagePercentage=map[cpu:95.52542372881356 memory:30.094216409416987 pods:49.09090909090909]
I0225 15:20:16.599134 1 lownodeutilization.go:101] "Criteria for a node under utilization" CPU=40 Mem=40 Pods=40
I0225 15:20:16.599151 1 lownodeutilization.go:102] "Number of underutilized nodes" totalNumber=1
I0225 15:20:16.599165 1 lownodeutilization.go:115] "Criteria for a node above target utilization" CPU=60 Mem=60 Pods=60
I0225 15:20:16.599175 1 lownodeutilization.go:116] "Number of overutilized nodes" totalNumber=2
I0225 15:20:16.599194 1 nodeutilization.go:223] "Total capacity to be moved" CPU=598 Mem=1058042675 Pods=55
I0225 15:20:16.599212 1 nodeutilization.go:226] "Evicting pods from node" node="kubernetes-worker-02" usage=map[cpu:2818m memory:4648Mi pods:54]
I0225 15:20:16.599337 1 nodeutilization.go:229] "Pods on node" node="kubernetes-worker-02" allPods=54 nonRemovablePods=25 removablePods=29
I0225 15:20:16.599348 1 nodeutilization.go:236] "Evicting pods based on priority, if they have same priority, they'll be evicted based on QoS tiers"
I0225 15:20:16.599725 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="cert-manager/cert-manager-cainjector-747cfdfd87-d6h9z"
I0225 15:20:16.599737 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="matrix/element-5c54494cd-bfdwz"
I0225 15:20:16.599746 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="jitsi/jitsi-jitsi-meet-web-5f55f4868b-frzbb"
I0225 15:20:16.599759 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="matrix/synapse-688c9c4fdb-9sfgp"
I0225 15:20:16.599789 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="vaultwarden/vaultwarden-7b7ccd55d7-fdv8b"
I0225 15:20:16.599800 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="cert-manager/cert-manager-5b6d4f8d44-9v9dn"
I0225 15:20:16.599806 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="cert-manager/cert-manager-webhook-67cb765ff6-f9p62"
I0225 15:20:16.599815 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="default/nfs-subdir-external-provisioner-84c486db85-sdmf2"
I0225 15:20:16.599822 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="kubegres-system/kubegres-1-0"
I0225 15:20:16.599830 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="default/metallb-controller-c55c89d-r5m8v"
I0225 15:20:16.599838 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="volt/volt-rest-api-599949d777-lgr6t"
I0225 15:20:16.599844 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="websites/nginx-static-55d776d678-qj28m"
I0225 15:20:16.599850 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="jitsi/jitsi-prosody-0"
I0225 15:20:16.599862 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="kubegres-system/kubegres-24-0"
I0225 15:20:16.599869 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="jitsi/jitsi-jitsi-meet-jvb-787cd69665-pkzxz"
I0225 15:20:16.599878 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="websites/ghost-58ff994-zms9d"
I0225 15:20:16.599884 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="media/ombi-76567f9b7f-dfmqh"
I0225 15:20:16.599890 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="media/prowlarr-bdf9bbf9b-lbkpr"
I0225 15:20:16.599899 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="media/radarr-d74b455bc-6xb92"
I0225 15:20:16.599905 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="websites/oblivioncoding-website-ffd849bb-x5gt2"
I0225 15:20:16.599912 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="media/jellyfin-f5d858979-jdb5b"
I0225 15:20:16.599923 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="jitsi/jitsi-jitsi-meet-jicofo-57c86f4886-gndjj"
I0225 15:20:16.599929 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="volt/volt-web-86bd775575-d28kn"
I0225 15:20:16.599936 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="monitoring/kube-state-metrics-86b69f4775-2xn7b"
I0225 15:20:16.599946 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="websites/fickipedia-mediawiki-64655f6955-zmp67"
I0225 15:20:16.599957 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="monitoring/blackbox-exporter-7d89b9b799-cbxnt"
I0225 15:20:16.599965 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="monitoring/prometheus-operator-68467b5c68-g2wqf"
I0225 15:20:16.599973 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="kubegres-system/kubegres-controller-manager-75db85776-2xrxn"
I0225 15:20:16.599980 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="cockroach-operator-system/cockroach-operator-manager-77f4957cdf-nqz7x"
I0225 15:20:16.600033 1 nodeutilization.go:240] "Evicted pods from node" node="kubernetes-worker-02" evictedPods=0 usage=map[cpu:2818m memory:4648Mi pods:54]
I0225 15:20:16.600043 1 nodeutilization.go:226] "Evicting pods from node" node="kubernetes-worker-01" usage=map[cpu:2112m memory:2719Mi pods:22]
I0225 15:20:16.600091 1 nodeutilization.go:229] "Pods on node" node="kubernetes-worker-01" allPods=22 nonRemovablePods=11 removablePods=11
I0225 15:20:16.600097 1 nodeutilization.go:236] "Evicting pods based on priority, if they have same priority, they'll be evicted based on QoS tiers"
I0225 15:20:16.600269 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="default/pod-gateway-94f59f4d6-86878"
I0225 15:20:16.600280 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="default/pod-gateway-webhook-f76bf444d-rfggw"
I0225 15:20:16.600286 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="health/uptime-kuma-78f999fbb6-v8w2n"
I0225 15:20:16.600291 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="volt/volt-rest-api-599949d777-bprh9"
I0225 15:20:16.600297 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="storage/nextcloud-55587dd4dd-7mh6s"
I0225 15:20:16.600303 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="mariadb/mariadb-54ccb4d6f4-4ff6k"
I0225 15:20:16.600309 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="vpn/terminal-799549dd4b-kqd6f"
I0225 15:20:16.600315 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="media/sonarr-79c45f864d-n6fqt"
I0225 15:20:16.600320 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="kubegres-system/kubegres-25-0"
I0225 15:20:16.600326 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="vpn/terminal-7785c9bff8-xkrw5"
I0225 15:20:16.600331 1 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="media/tdarr-7b8b6df6b4-fdwr5"
I0225 15:20:16.600341 1 nodeutilization.go:240] "Evicted pods from node" node="kubernetes-worker-01" evictedPods=0 usage=map[cpu:2112m memory:2719Mi pods:22]
I0225 15:20:16.600347 1 lownodeutilization.go:164] "Total number of pods evicted" evictedPods=0
I0225 15:20:16.600357 1 duplicates.go:110] "Processing node" node="kubernetes-cp-01"
I0225 15:20:16.600393 1 duplicates.go:110] "Processing node" node="kubernetes-worker-01"
I0225 15:20:16.600463 1 duplicates.go:110] "Processing node" node="kubernetes-worker-02"
I0225 15:20:16.600631 1 descheduler.go:291] "Number of evicted pods" totalEvicted=0
panic: close of closed channel
goroutine 73 [running]:
sigs.k8s.io/descheduler/pkg/descheduler.Run.func1()
/go/src/sigs.k8s.io/descheduler/pkg/descheduler/descheduler.go:76 +0x3c
created by sigs.k8s.io/descheduler/pkg/descheduler.Run
/go/src/sigs.k8s.io/descheduler/pkg/descheduler/descheduler.go:74 +0x165
```

**Comment by damemi** [comment]
Hi, we are working to publish a patch to fix this. Please see https://github.com/kubernetes-sigs/descheduler/issues/741 and https://github.com/kubernetes-sigs/descheduler/issues/728.

For a workaround in the mean time, you can run the Descheduler as a Deployment instead of a CronJob (if possible)

**Comment by Y0ngg4n** [comment]
ah thank you
