### ISSUE TITLE
deschduler jobs panic

### ISSUE THREAD

**Issue by matti** [kubernetes-sigs/descheduler#775]
**What version of descheduler are you using?**

descheduler version: k8s.gcr.io/descheduler/descheduler:v0.23.0

**Does this issue reproduce with the latest release?**
yes

**Which descheduler CLI options are you using?**
https://github.com/matti/eksler/blob/496530189c5ad82f9a7d62d4e192f83bdf7ae277/helm/charts/descheduler-1/values.yml

but change Deployment to CronJob

**Please provide a copy of your descheduler policy config file**
see above

**What k8s version are you using (`kubectl version`)?**

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:51:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

Installed descheduler chart v0.23.1 with values https://github.com/matti/eksler/blob/496530189c5ad82f9a7d62d4e192f83bdf7ae277/helm/charts/descheduler-1/values.yml
(but changed Deployment to CronJob)

**What did you expect to see?**

Descheduler to create pods every minute that don't crash

**What did you see instead?**

Half of the pods fail with:

```
I0321 13:07:04.180042       1 named_certificates.go:53] "Loaded SNI cert" index=0 certName="self-signed loopback" certDetail="\"apiserver-loopback-client@1647868024\" [serving] validServingFor=[apiserver-loopback-client] issuer=\"apiserver-loopback-client-ca@1647868023\" (2022-03-21 12:07:03 +0000 UTC to 2023-03-21 12:07:03 +0000 UTC (now=2022-03-21 13:07:04.17999895 +0000 UTC))"
I0321 13:07:04.180105       1 secure_serving.go:200] Serving securely on [::]:10258
I0321 13:07:04.180375       1 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I0321 13:07:04.191690       1 reflector.go:219] Starting reflector *v1.Namespace (0s) from k8s.io/client-go/informers/factory.go:134
I0321 13:07:04.191710       1 reflector.go:255] Listing and watching *v1.Namespace from k8s.io/client-go/informers/factory.go:134
I0321 13:07:04.192008       1 reflector.go:219] Starting reflector *v1.PriorityClass (0s) from k8s.io/client-go/informers/factory.go:134
I0321 13:07:04.192021       1 reflector.go:255] Listing and watching *v1.PriorityClass from k8s.io/client-go/informers/factory.go:134
I0321 13:07:04.192203       1 reflector.go:219] Starting reflector *v1.Pod (0s) from k8s.io/client-go/informers/factory.go:134
I0321 13:07:04.192215       1 reflector.go:255] Listing and watching *v1.Pod from k8s.io/client-go/informers/factory.go:134
I0321 13:07:04.292237       1 node.go:46] "Node lister returned empty list, now fetch directly"
I0321 13:07:04.301805       1 descheduler.go:266] Building a pod evictor
I0321 13:07:04.301864       1 failedpods.go:70] "Processing node" node="ip-192-168-16-118.eu-north-1.compute.internal"
I0321 13:07:04.301882       1 failedpods.go:70] "Processing node" node="ip-192-168-33-95.eu-north-1.compute.internal"
I0321 13:07:04.301898       1 failedpods.go:70] "Processing node" node="ip-192-168-87-139.eu-north-1.compute.internal"
I0321 13:07:04.301929       1 toomanyrestarts.go:90] "Processing node" node="ip-192-168-16-118.eu-north-1.compute.internal"
I0321 13:07:04.301969       1 toomanyrestarts.go:90] "Processing node" node="ip-192-168-33-95.eu-north-1.compute.internal"
I0321 13:07:04.302017       1 toomanyrestarts.go:90] "Processing node" node="ip-192-168-87-139.eu-north-1.compute.internal"
I0321 13:07:04.302076       1 descheduler.go:291] "Number of evicted pods" totalEvicted=0
I0321 13:07:04.302262       1 reflector.go:225] Stopping reflector *v1.Pod (0s) from k8s.io/client-go/informers/factory.go:134
I0321 13:07:04.302349       1 reflector.go:225] Stopping reflector *v1.Namespace (0s) from k8s.io/client-go/informers/factory.go:134
I0321 13:07:04.302387       1 reflector.go:225] Stopping reflector *v1.PriorityClass (0s) from k8s.io/client-go/informers/factory.go:134
panic: close of closed channel

goroutine 98 [running]:
sigs.k8s.io/descheduler/pkg/descheduler.Run.func1()
	/go/src/sigs.k8s.io/descheduler/pkg/descheduler/descheduler.go:76 +0x3c
created by sigs.k8s.io/descheduler/pkg/descheduler.Run
```

**Comment by damemi** [comment]
Hi @matti, please try updating to `v0.23.1`. This looks like a similar issue as to what was fixed in https://github.com/kubernetes-sigs/descheduler/pull/731 (https://github.com/kubernetes-sigs/descheduler/issues/728)

**Comment by matti** [comment]
@damemi thanks, upgrading helm chart to 0.23.2 which has 0.23.1 fixes this

**Comment by damemi** [comment]
> @damemi it's confusing that installing chart version 0.23.1 gives you 0.23.0 (#776)

Yeah, sometimes there are changes to the Helm chart (like exposing a new field) that don't involve an update to the appVersion (ie, no new image was built for it), so there can be some minor version skew there since the container version is managed entirely separate from the Helm chart
